[feat✨] : 회원가입 인증수단 개발완료
Gaship/gaship-auth pull request #1
Opened 2022-07-13 11:08 UTC by oct-sky-out

## 회원가입 인증수단.
---
### 1. 이메일 인증
- redis를 이용한 인증 번호 저장.
- 회원이 링크를 누르면 해당 자동으로 인증 완료.

### 2. 예외사항
- 이메일 인증 요청시 형식을 다르게하여 요청시 이메일 제공 서비스에서 에러 사유를 줌
- 이메일 검증시 인증 코드가 레디스에 저장되어있지않거나 이미 파기되었을 시 예외를 던짐.

2022-07-13 11:10 UTC, oct-sky-out commented
회원가입이 로그인 브랜치에서 따온 것이라 첫 부분의 커밋이 미완성된 로그인 기능입니다.
따라서 아래의 커밋부터 보심이 좋을듯싶습니다!

[a99540d](https://github.com/Gaship/gaship-auth/pull/1/commits/a99540dda4ff2344f0f09ce7bf7c966b7a7244e4)

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +    private Date getExpireDate(long seconds){
Date -> LocalDate 를 사용해보면 어떨까요?

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +            .signWith(createKey)
signWith (createKey) <-- cloud secure key manager 이용해보면 어떨까요?

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        claims.put("email", userDetails.getEmail());
id <-- 회원을 식별할 수 있는 고유 번호라면  email은 빼버리면 어떨까요?
id를 가지고 인증서버에서 회원정보를 얻어내는 방식으로 처리해도 될거같아요.

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +    private Date getExpireDate(long seconds){
Date 보다는 LocalDate 사용해보세요~

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/verify/service/impl/VerifyServiceImpl.java
> +            Map.of("link", "http://localhost:8080/members/signUp/email-verify/" + verifyCode);
하드코딩 보다는 properties
profile 분리-> 개발환경과  운영환경 세팅해보세요~

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/verify/util/EmailSenderUtil.java
> +    private static final String MAIL_SENDER_BASE_URL = "https://api-mail.cloud.toast.com";
mail 관련해서  환경설정 -> properties에 관리해보세요

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/test/java/shop/gaship/gashipauth/util/WebClientUtilTest.java
> +            "https://jsonplaceholder.typicode.com",
https://jsonplaceholder.typicode.com 당장은 문제가 없는데. 혹시 typicode.com(url 변경된다던가... ) 문제가 생기면 어떻게 될까요?

2022-07-14 00:37 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/verify/exception/EmailVerificationImpossibleException.java
> +        super("이메일 인증시간이 만료되거나, 검증이 불가능합니다.");
이메일 인증시간이 만료되거나, 검증이 불가능합니다. <-- private static final 상수로 만들어서 사용해도 괜찮을거 같아요.

2022-07-14 03:57 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +    private Date getExpireDate(long seconds){
네 Date 객체를 지양하니 LocalDate로 지정하는것이 좋겠네요.

2022-07-14 04:07 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +            .signWith(createKey)
createKey는 AutentificationConfig에서 제작되며, 해당 키값은 cloud secure key manager로 보호되고있는데, 혹시 이 방법이 틀렸는지 확인 받을 수 있을까요?

2022-07-14 04:07 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        claims.put("email", userDetails.getEmail());
사용용도가 빈번할거같아서 넣었는데, 만약 정말로 사용이 빈번해져 요청 횟수가 많아진다면 라운드 트립이 빈번하게 발생될 것 같아 그때는 이메일을 넣어보는 것으로 고려해보겠습니다.

2022-07-14 04:07 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/verify/exception/EmailVerificationImpossibleException.java
> +        super("이메일 인증시간이 만료되거나, 검증이 불가능합니다.");
상수로 만드는 편이 확실히 나을것같네요! 감사합니다.😺

2022-07-14 04:07 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/verify/service/impl/VerifyServiceImpl.java
> +            Map.of("link", "http://localhost:8080/members/signUp/email-verify/" + verifyCode);
저번에 말씀 하셨던 부분의 효용이 여기서 드러나네요.... 운영환경 세팅해보겠습니다.

2022-07-14 04:07 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/verify/util/EmailSenderUtil.java
> +    private static final String MAIL_SENDER_BASE_URL = "https://api-mail.cloud.toast.com";
이거또한 properties로 관리하겠습니다. 하드코딩때문에 불편하고, 애매한 부분이었는데 잘 긁어주셨네요 감사합니다.🙇‍♂️

2022-07-14 04:07 UTC, oct-sky-out commented on src/test/java/shop/gaship/gashipauth/util/WebClientUtilTest.java
> +            "https://jsonplaceholder.typicode.com",
해당 테스트의 케이스를 저희 서비스의 api로 바꿀까 고려하고있습니다. 테스트 관리도 중요하지만, 해당 테스트는 예제 및 단순 검증이므로 테스트 케이스를 바꾸는 것은 나중에 미뤄보도록하겠습니다 감사합니다.

2022-07-14 04:12 UTC, nhn-academy-marco commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        claims.put("email", userDetails.getEmail());
이메일과 회원아이디가 중복 식별자라서 문제가 된다기 보다는 .. 
개인정보가 Token에 담기는거 자체를 제거해보자..라는 의미로 의견드렸어요^^

2022-07-14 04:16 UTC, HoFe-U approved these changes

2022-07-14 04:34 UTC, qnt012 commented on src/main/java/shop/gaship/gashipauth/config/AuthenticationConfig.java
> +                "/keymanager/v1.0/appkey/" + appKey + "/secrets/" + mailKeypair,
urn이 동일한 부분이 있어서 변수나 메소드로 빼도 좋을 것 같아요. StringBuilder를 사용하는 것도 괜찮아 보여요.

2022-07-14 04:34 UTC, qnt012 commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendDto.java
> +public class EmailSendDto {
class 상위에 @Builder를 다는 것 보다 메소드 상위에 사용하는 건 어떨까 싶어요.

2022-07-14 04:45 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/config/AuthenticationConfig.java
> +                "/keymanager/v1.0/appkey/" + appKey + "/secrets/" + mailKeypair,
네, 확실히 이부분은 수정이 필요함을 사용 할 때 마다 느끼네요 🥲

2022-07-14 04:51 UTC, JoisFe commented on src/test/java/shop/gaship/gashipauth/util/JwtTokenUtilTest.java
> +@SpringBootTest
@SpringBootTest를 사용하지 않고 테스트 할 수 없을까요?

2022-07-14 04:56 UTC, oct-sky-out commented on src/test/java/shop/gaship/gashipauth/util/JwtTokenUtilTest.java
> +@SpringBootTest
https://github.com/Gaship/gaship-shopping-mall/pull/2#discussion_r920732491

위 댓글을 참고해주세요

2022-07-14 13:59 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/advisor/VerifyAdvisor.java
> +        RuntimeException.class
위 3개의 예외경우를 제외하고 다른 checkedException이 발생할수도 있는데 그경우에는 따로 예외처리를 안하고 비정상종료를 시키게 될듯하네요!
Exception.class만 처리해주는 defaultException 메서드도 하나 생성하면 예기치 못한 상황도 잡아낼수 있지 않을까요?ㅎㅎ

2022-07-14 14:02 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendDto.java
> +public class EmailSendDto {
세가지 필드를 모두 Build형으로 주입받을 계획이라면 이대로 사용하는것도 나쁘지 않다고 생각해요~

2022-07-14 14:02 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendDto.java
> +public class EmailSendDto {
세가지 필드를 모두 Build형으로 주입받을 계획이라면 이대로 사용하는것도 나쁘지 않다고 생각해요~

2022-07-14 14:05 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/verify/advisor/VerifyAdvisor.java
> +        RuntimeException.class
@jun1718 좋은 지적 감사합니다. 반영하도록 하겠습니다!

2022-07-14 14:05 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/exception/EmailVerificationImpossibleException.java
> +        super("이메일 인증시간이 만료되거나, 검증이 불가능합니다.");
기왕만드는김에 예외 메세지들을 모아놓는 예외메세지 상수 팩토리가 하나 있어도 좋을것 같네요 ^__^

2022-07-14 14:08 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendSuccessfulDto.java
> +}
개인적으로 궁금한부분인데 inner class나 일반클래스로 합성하지않고 static class를 사용하면 어떤 이점이 있어서 사용하신걸까요?

2022-07-14 14:12 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/config/AuthenticationConfig.java
> +@PropertySource("classpath:application.properties")
application.properties 형식과 그 자손프로퍼티들은 @PropertySource를 적용하지 않아도 자동적으로 매핑해서 찾는데 명시를 해준 이유가 있으신지 궁금합니다!

2022-07-14 14:16 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/dto/JwtTokenDto.java
> +@Data
jwttoken을 통째로 다른 토큰과 비교할 일이 있을까요? redis에서 jwt를 얻어와서 비교를 할때도 accessToken 또는 refreshToken 단일로 가져와서 비교를 하는걸로 알고 있는데 Data를 써서 HashAndEquals나 ToString AllArg settergetter 등의 롬복이 모두 들어가는것은 역할을 혼동하게 하고 리소스 낭비로 이어질수도 있을것 같습니다! 아니면 다른 필요에 의해서 Data annotaion을 달아주신건지 궁금합니다!!!

2022-07-14 14:22 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/util/dto/RequestSuccessDto.java
> +    private final String requestStatus = "success";
이미 Allarg나 RequiredArg가 없어서 Noarg상태인걸로 보입니다. 지워도 될것같습니다! 추가로 requestSuccess라고 명명하면 우리가 이메일 api에 보내는 요청이 성공했다는 의미인것 같은데 request는 실제 통신의 요청이고 send가 이루어졌다는 것을 조금더 강조하고 가독성을 높이기위해서 SendSuccessDto로 명명해도 괜찮을것 같습니다ㅎㅎ

2022-07-14 14:34 UTC, jun1718 commented on src/main/resources/application.properties
> +secure.mail.email-notification-secure-key=61621bace5994b3eaa7aebd3872db24b
이부분은 내일이나 팀원들과 논의해서 application-dev.properties application-prod.properties같은 형태로 분리해서 action으로 매때마다 혹은 통합테스트때는 application-test.properties를 이용ㅎ는 식으로 정리하면 좋을듯 합니다!

2022-07-14 14:39 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        headerMap.put("alg", "HS256");
이건 지극히 개인적인건데 typ와 alg로 3글자식만 맞춘거는 코딩습관이신가요? 혹은 요즘 대세인가요?

2022-07-14 14:46 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/dto/SignInSuccessUserDetailsDto.java
> +}
이제 토큰에 email값을 빼고 회원번호만 넣기로 했으니 이곳에도 email이 빠지면 되겠군요! 로그인했을때는 앞으로 auth 서버로 요청할때 회원번호와 권한 두가지만 파라미터로 담아서 보내겠습니다ㅎㅎ

2022-07-14 14:51 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/service/impl/TokenServiceImpl.java
> +    }
두 메서드를 합쳐도 5줄가량나오는데 동기적으로 메소드가 연결되어 있는 것으로 보아 메소드를 합치는 것도 나쁘지 않을것 같네요!

2022-07-14 14:51 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendSuccessfulDto.java
> +}
Response 받는 데이터 형태를 본따서 가독성 좋게 만드려는 취지에서 이렇게 했어요

2022-07-14 14:51 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/dto/JwtTokenDto.java
> +@Data
혹시 어떤 어노테이션을 사용하면 될까요? 추천부탁드립니다.
전 Getter, AllArgsConstructor, NoArgsConstructor면 충분할거같은데 말이죠

2022-07-14 14:51 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/util/dto/RequestSuccessDto.java
> +    private final String requestStatus = "success";
음 전 RequestSuccessDto 이름이 마치 클라이언트의 요청을 수행완료했다는 의미로 해석 시키기위해 만들었는데 잘 전달이 안된거같네요 SendSuccessDto 도 어떤 것을 send하는지에 대한 뉘앙스라 차라리 SuccessStatusDto는 어떨까요? 더 좋은 이름이 있으면 추천 부탁드립니다.

2022-07-14 14:51 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        headerMap.put("alg", "HS256");
https://jwt.io

공식문서에 이렇게 해라고 컨벤션으로 나와있는데말이죠....

2022-07-14 14:51 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/dto/SignInSuccessUserDetailsDto.java
> +}
네, 그렇네요 피드백 감사합니다.
참고하겠습니다.

2022-07-14 14:52 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/service/impl/TokenServiceImpl.java
> +    }
합치면 두 메서드를 사실 하나의 메소드에서 3줄짜리로도 만들수 있겠네요! 물론 가독성은 쪼금 안좋아질수도 있지만은 메소드체이닝을 굳이 걸지 않아도 된다는 이점이 있네요!

2022-07-14 14:56 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/config/AuthenticationConfig.java
> +@PropertySource("classpath:application.properties")
이걸 나중에 알았는데 이거도 적용해야겠네요.

2022-07-14 14:56 UTC, jun1718 requested changes
전체적으로 쭉 훑어봤습니다. 너무 아름다운 코드였어요.
진심과 정성이 느껴졌습니다. 역시 실력자 민수님!

하지만 사실 가장 궁금했던건 controller단에서 api 요청 url은 뭘로했는지가 제일 궁금했는데(이제 로그인쪽에서 갖다 붙여야해서..ㅎ) controller는 아직 안만드셨더군요!
그쪽도 완료되면 다시 보겠습니다ㅎㅎ
그밖에도 민수님 생각이 궁금해서 답변남긴것들있는데 확인해주시면 감사하겠습니다.

2022-07-14 15:02 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/advisor/VerifyAdvisor.java
> +        RuntimeException.class
@oct-sky-out 넵!

2022-07-14 15:03 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/verify/dto/EmailSendSuccessfulDto.java
> +}
그렇군요. 확실히 가독성이 매우 좋아보입니다 ㅎㅎ 한수배워갑니다.

2022-07-14 15:07 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/dto/JwtTokenDto.java
> +@Data
동감합니다. 세개만있어도 완벽하게 되겠습니다ㅎㅎ 다만 [src/main/java/shop/gaship/gashipauth/token/service/impl/TokenServiceImpl.java](https://github.com/Gaship/gaship-auth/pull/1/files/f4040db3efbf87a8b8e5ca8d39934f33490029a2#diff-0afdacb2f74024bfaf37a7c6a4bb3065b1c2ea895416088d97549c968b559e73)의 36,37번코드에서 setter로 accesstoken과 refreshtoken을 주입하고있어서 저부분을 allarg로 받는 형식으로 바꾸면 완벽하겠네요!

2022-07-14 15:08 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/util/dto/RequestSuccessDto.java
> +    private final String requestStatus = "success";
아 그렇군요 그런의미라면 RequestSUccessDto자체가 더 직관적이고 좋은것 같습니다 ㅎㅎ SuccessStatus하면 404같은 숫자가 티어나올것 같은 느낌이 들수도 있겠네요..ㅋㅋ

2022-07-14 15:09 UTC, jun1718 commented on src/main/java/shop/gaship/gashipauth/token/util/JwtTokenUtil.java
> +        headerMap.put("alg", "HS256");
아하 감사합니다 공식문서가 별다줄이군요.

2022-07-14 15:12 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/dto/JwtTokenDto.java
> +@Data
확실히 그렇군요... 하지만 단순히 Setter라서 적대감을 드러낸다기 보단 저 상황에서는 Setter를 사용해도 어감, 사용하는 용도가 나쁘지는않아보이지만 다른방법을 좀 강구해보자면 AllArgsConstructor를 이용하는 방법이 더 좋아보이긴하군요!

2022-07-14 15:13 UTC, oct-sky-out commented on src/main/resources/application.properties
> +secure.mail.email-notification-secure-key=61621bace5994b3eaa7aebd3872db24b
네 이건 내일 이슈에 올려야할 사항인거같습니다. 아직 컨벤션이 제대로 잡히지 않아 걱정이긴하네요😅

2022-07-14 15:16 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipauth/token/dto/JwtTokenDto.java
> +@Data
방금 고쳤는데요, 확실히 줄었고 더 보기 좋네요 덕분에 깔끔해졌습니다!

2022-07-15 05:16 UTC, qnt012 approved these changes

2022-07-15 13:50 UTC, merged